# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb-dev-tutorial',
                'doc_host': 'https://frh-1.github.io',
                'git_url': 'https://github.com/frh-1/nb-dev-tutorial',
                'lib_path': 'nb_dev_tutorial'},
  'syms': {'nb_dev_tutorial.core': {'nb_dev_tutorial.core.foo': ('core.html#foo', 'nb_dev_tutorial/core.py')}}}
